In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


In [13]:
#Task 01 : Use numpy to create a 3×3 matrix of random integers between 1 and 50.
Matrix = np.random.randint(1, 50, (3, 3))
print(Matrix)

[[ 9 10  1]
 [43 41 37]
 [17 37 48]]


In [14]:
#Task 2 : Use numpy to create a 3×3 matrix of random integers between 1 and 50. With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.
np.random.seed(10)
Matrix = np.random.randint(1, 50, (3, 3))
print(Matrix)

[[10 37 16]
 [ 1 29 26]
 [30 49 30]]


# **Explanation:**
The code performs two tasks using NumPy to generate a 3×3 matrix of random integers between 1 and 50.


---


### **Task 1: Generating a Random Matrix Without a Fixed Seed**
When NumPy generates a 3×3 matrix of random integers between 1 and 50 without a fixed seed, the values will change each time the code is executed.

This happens because no specific starting point is set for the random number generator. As a result, each run produces a different set of random numbers, making the output unpredictable. Every time the program runs, NumPy initializes its random number generator differently, leading to a unique matrix with new values.

This behavior is useful in scenarios where fresh randomness is needed, such as simulations, data augmentation, or generating unpredictable test cases.



---



### **Task 2: Generating a Random Matrix With a Fixed Seed (np.random.seed(10))**
When we use np.random.seed(10) before generating a random matrix, we are setting a fixed starting point for NumPy’s random number generator. This ensures that the same matrix is generated every time the code runs, making the results predictable and repeatable.

**How It Works**

Random Number Generator:


*   NumPy generates random numbers using a mathematical formula.
*   These numbers are not truly random but are based on an initial value called the seed.







Setting a Seed (np.random.seed(10)):


*   The seed acts as a starting point, ensuring that NumPy produces the same sequence of random numbers every time.
*   This guarantees that the matrix remains consistent across multiple runs of the code.





**Why Use a Seed?**

✔ Reproducibility: Helpful for testing and debugging, ensuring results don’t change unexpectedly.

✔ Consistency: Allows different people running the same code to get identical results.

✔ Controlled Randomness: Useful in machine learning, simulations, and research, where repeatable outcomes are important.